### ISSUE TITLE
Local storage game state isn't cleared the next day

### ISSUE THREAD

**Issue by diondiondion** [hannahcode/wordle#14]
Hi Hannah, thanks for your work on this! Your project enabled me to spin up a German version of Wordle very easily.

I just ran into an issue in my fork where the game state that's saved in local storage persists into the next day. I.e. it's not cleared when a new word is enabled, making it impossible to solve the new word from scratch without manually clearing the site's localStorage.

I'm happy to try and create a PR for this tomorrow if I get around to it before you do.

**Comment by hannahcode** [comment]
Hi @diondiondion, thanks so much for reaching out! I'm glad you found the code useful. I just did a quick [fix for this issue here](https://github.com/hannahcode/wordle/commit/c8e415c737dbff0a44b10b46e8e7dfbde1fedde2). Please let me know if it is still giving you issues, I appreciate you bringing this to my attention.
